image:
  repository: homebridge/homebridge
  tag: 2025-02-26

ingress:
  main:
    enabled: true
    hosts:
      - host: "hb.mnara.ca"
        paths:
          - path: "/"
  tls:
    secretName: "wildcard-mnara-ca-tls"

hostNetwork: true

persistence:
  config:
    enabled: true
