image:
  tag: "1.23.13-debian"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: "uptime.mnara.ca"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "wildcard-mnara-ca-tls"
