defaultRules:
  rules:
    etcd: false

kubeEtcd:
  enabled: false

grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - "grafana.internal.mnara.ca"
    tls:
      - hosts: 
        - "grafana.internal.mnara.ca"

alertmanager:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - "alertmanager.internal.mnara.ca"
    tls:
      - hosts:
        - "alertmanager.internal.mnara.ca"

prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - "prometheus.internal.mnara.ca"
    tls:
      - hosts:
        - "prometheus.internal.mnara.ca"
