image:
  tag: "2023.9.3"

ingress:
  main:
    enabled: true
    annotations:
      "nginx.org/websocket-services": "home-assistant"
    hosts:
      - host: "ha.mnara.ca"
        paths:
          - path: "/"
  tls:
    secretName: "wildcard-mnara-ca-tls"

hostNetwork: true

persistence:
  config:
    enabled: true

dnsPolicy: "ClusterFirstWithHostNet"

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "NET_RAW", "NET_BROADCAST"]
