version: 14.0.1
image:
  tag: "2025.2.5"

ingress:
  main:
    enabled: true
    annotations:
      "nginx.org/websocket-services": "home-assistant"
    hosts:
      - host: "ha.mnara.ca"
        paths:
          - path: "/"
  tls:
    secretName: "wildcard-mnara-ca-tls"

hostNetwork: true

persistence:
  config:
    enabled: true
  bluetooth:
    enabled: true
    readOnly: true
    hostPath: /run/dbus
    mountPath: /run/dbus
    type: hostPath

dnsPolicy: "ClusterFirstWithHostNet"

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "NET_RAW", "NET_BROADCAST"]
