name: Docker

on:
  push:
    branches: [ 'main' ]
    paths:
      - "terraform/modules/cloudflare-ddns/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: inssein/mainframe/cloudflare-ddns

jobs:
  cloudflare-ddns:
    name: mainframe/cloudflare-ddns
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: terraform/modules/cloudflare-ddns
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
