name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup k3s
        uses: nolar/setup-k3d-k3s@v1

      - name: Test Whoami Module
        run: go test -v -timeout 30m
        working-directory: ./terraform/modules/whoami/test

      - name: Test Cloudflare DDNS Module
        run: go test -v -timeout 30m
        working-directory: ./terraform/modules/cloudflare-ddns/test